#!/usr/bin/env ruby 
# Create a pull request from the current repo and branch
# Requires gem atlassian-stash and ~/.stashconfig.yml
# 
# I use this cat .stashconfig.yml
# ---
# stash_url: https://git.nordstrom.net
# username: xmjg
# ssl_no_verify: true

cookbook = File.basename(Dir.getwd)
puts "In cookbook #{cookbook}"

rubocop_rc = system("rubocop -a")
foodcritic_rc = system("foodcritic .")
exit unless rubocop_rc && foodcritic_rc

branch = `git rev-parse --abbrev-ref HEAD 2>/dev/null`.split(/\n/)[0]
description = `git log -1 --pretty=%B --oneline`
description.gsub!(/'/, '')
puts `git push origin #{branch}`

# Add Jeff, Jim
base = %w() # @UPPERCASE user ids
others = []

if cookbook =~ /^oa_/
  others = others | %w()
end

if cookbook =~ /rewards/
  others = others | %w()
end

if cookbook =~ /ldom/
  others = others | %w()
end

# Randomly select 2 others
others = others | %w().sample(2)
puts "Using branch #{branch} with these approvers #{base} #{others}"
puts "Description #{description}"
puts "Pull request for branch #{branch} Password:"
puts `stash pull-request -d '#{description}' #{branch} master #{base.concat(others).join(' ')} 2>&1`
#  puts `stash pull-request #{branch} -d '#{description}' master 2>&1`
